import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Mailing Label Template (AI-Generated)
 * Features standard mailing label layout with sender and recipient
 */
export const mailingLabelTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'label-mailing-001',
    name: 'Mailing Label',
    description: 'Standard mailing label with sender and recipient addresses for business correspondence',
    category: 'labels',
    thumbnail: undefined,
    tags: ['label', 'mailing', 'address', 'business', 'envelope'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'label',
    aiDefinition: {
      style: 'mailing',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#1f2937',
        secondary: '#6b7280',
        accent: '#d1d5db',
        textDark: '#1f2937',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 16,
        headingSize: 11,
        subheadingSize: 10,
        bodySize: 10,
        smallSize: 9,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['from-label', 'from-address'],
        main: ['to-label', 'to-address'],
      },
    },
  },
  // Content is generated by AI based on user input
};
