import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Shipping Label Template (AI-Generated)
 * Features professional shipping label with tracking info
 */
export const shippingLabelTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'label-shipping-001',
    name: 'Shipping Label',
    description: 'Professional shipping label with tracking info, carrier details, and package specifications',
    category: 'labels',
    thumbnail: undefined,
    tags: ['label', 'shipping', 'package', 'delivery', 'tracking'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'label',
    aiDefinition: {
      style: 'shipping',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#1f2937',
        secondary: '#dc2626',
        accent: '#d1d5db',
        textDark: '#1f2937',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 18,
        headingSize: 14,
        subheadingSize: 12,
        bodySize: 10,
        smallSize: 8,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['company', 'ship-from'],
        main: ['ship-to', 'tracking', 'weight'],
      },
    },
  },
  // Content is generated by AI based on user input
};
