import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Corporate Letterhead Template (AI-Generated)
 * Features professional business letterhead with header and footer
 */
export const corporateLetterheadTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'letterhead-corporate-001',
    name: 'Corporate Letterhead',
    description: 'Professional corporate letterhead with header, footer, and business correspondence layout',
    category: 'letterheads',
    thumbnail: undefined,
    tags: ['letterhead', 'corporate', 'business', 'professional', 'header'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'letterhead',
    aiDefinition: {
      style: 'corporate',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#1e3a5f',
        secondary: '#64748b',
        accent: '#0ea5e9',
        textDark: '#374151',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 28,
        headingSize: 14,
        subheadingSize: 12,
        bodySize: 11,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['company-name', 'tagline', 'contact-info'],
        main: ['date', 'recipient', 'salutation', 'body', 'closing', 'signature'],
        footer: ['website'],
      },
    },
  },
  // Content is generated by AI based on user input
};
