import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Personal Letterhead Template (AI-Generated)
 * Features elegant centered design for personal correspondence
 */
export const personalLetterheadTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'letterhead-personal-001',
    name: 'Personal Letterhead',
    description: 'Elegant personal letterhead with centered design for individual correspondence',
    category: 'letterheads',
    thumbnail: undefined,
    tags: ['letterhead', 'personal', 'elegant', 'individual', 'correspondence'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'letterhead',
    aiDefinition: {
      style: 'personal',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#374151',
        secondary: '#6b7280',
        accent: '#9ca3af',
        textDark: '#374151',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 32,
        headingSize: 14,
        subheadingSize: 12,
        bodySize: 11,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['name', 'address', 'contact-info'],
        main: ['date', 'salutation', 'body', 'closing', 'signature'],
      },
    },
  },
  // Content is generated by AI based on user input
};
