import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Freelancer Invoice Template (AI-Generated)
 * Features project-focused layout with hourly tracking
 */
export const freelancerInvoiceTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'invoice-freelancer-001',
    name: 'Freelancer Invoice',
    description: 'Perfect for freelancers and consultants with hourly rates, project tracking, and professional styling',
    category: 'invoices',
    thumbnail: undefined,
    tags: ['invoice', 'freelance', 'hourly', 'consultant', 'project'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'invoice',
    aiDefinition: {
      style: 'freelancer',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#7c3aed',
        secondary: '#a78bfa',
        accent: '#1e1b4b',
        textDark: '#1e1b4b',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 28,
        headingSize: 14,
        subheadingSize: 13,
        bodySize: 11,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['freelancer-info', 'invoice-badge', 'invoice-details'],
        main: ['client-info', 'project-info', 'items-table', 'totals'],
        footer: ['payment-terms', 'notes'],
      },
    },
  },
  // Content is generated by AI based on user input
};
