import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Professional Invoice Template (AI-Generated)
 * Features clean corporate design with detailed line items
 */
export const professionalInvoiceTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'invoice-professional-001',
    name: 'Professional Invoice',
    description: 'Elegant corporate invoice with detailed line items, clean layout, and professional styling',
    category: 'invoices',
    thumbnail: undefined,
    tags: ['invoice', 'billing', 'professional', 'corporate', 'detailed'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'invoice',
    aiDefinition: {
      style: 'professional',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#0ea5e9',
        secondary: '#64748b',
        accent: '#0f172a',
        textDark: '#0f172a',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 26,
        headingSize: 14,
        subheadingSize: 13,
        bodySize: 11,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['company-info', 'invoice-badge', 'invoice-details'],
        main: ['client-info', 'items-table', 'totals'],
        footer: ['payment-terms', 'notes'],
      },
    },
  },
  // Content is generated by AI based on user input
};
