import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Contact Form Template (AI-Generated)
 * Features professional contact form with customizable fields
 */
export const contactFormTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'form-contact-001',
    name: 'Contact Form',
    description: 'Professional contact form for businesses and organizations with customizable fields',
    category: 'forms',
    thumbnail: undefined,
    tags: ['form', 'contact', 'business', 'inquiry', 'customer'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'form',
    aiDefinition: {
      style: 'contact',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#2563eb',
        secondary: '#64748b',
        accent: '#1e40af',
        textDark: '#1e293b',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 28,
        headingSize: 16,
        subheadingSize: 14,
        bodySize: 12,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['company-name', 'form-title', 'description'],
        main: ['form-fields'],
        footer: ['submit-button', 'privacy-note'],
      },
    },
  },
  // Content is generated by AI based on user input
};
