import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Registration Form Template (AI-Generated)
 * Features event registration form with ticket types and customizable sections
 */
export const registrationFormTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'form-registration-001',
    name: 'Registration Form',
    description: 'Event registration form with ticket options, sections, and customizable fields',
    category: 'forms',
    thumbnail: undefined,
    tags: ['form', 'registration', 'event', 'signup', 'conference'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'form',
    aiDefinition: {
      style: 'registration',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#059669',
        secondary: '#6b7280',
        accent: '#047857',
        textDark: '#1f2937',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 28,
        headingSize: 16,
        subheadingSize: 14,
        bodySize: 12,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['event-info', 'form-title', 'description'],
        main: ['registration-types', 'form-sections', 'form-fields'],
        footer: ['submit-button', 'privacy-note'],
      },
    },
  },
  // Content is generated by AI based on user input
};
