import type { AITemplateMetadata, AnyTemplateData } from '../../../types/templates';

/**
 * Classic Resume Template (AI-Generated)
 * Traditional single-column format suitable for all industries
 */
export const classicResumeTemplate: AnyTemplateData = {
  metadata: {
    id: 'resume-classic-001',
    name: 'Classic Resume',
    description: 'Traditional resume format with centered header and clean sections',
    category: 'resumes',
    thumbnail: undefined,
    tags: ['resume', 'cv', 'classic', 'traditional', 'professional', 'single-column'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-01-15T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'resume',
    aiDefinition: {
      style: 'classic',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#1f2937',
        secondary: '#6b7280',
        accent: '#1f2937',
        textDark: '#1f2937',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 28,
        headingSize: 12,
        subheadingSize: 12,
        bodySize: 11,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['name', 'contact'],
        main: ['objective', 'experience', 'education', 'skills'],
      },
    },
  } as AITemplateMetadata,
  // Content is generated by AI - no static content
};
