import type { AITemplateMetadata, AnyTemplateData } from '../../../types/templates';

/**
 * Creative Resume Template (AI-Generated)
 * Bold, colorful design with header background for creative professionals
 */
export const creativeResumeTemplate: AnyTemplateData = {
  metadata: {
    id: 'resume-creative-001',
    name: 'Creative Resume',
    description: 'Bold, colorful resume design with header background for creative professionals',
    category: 'resumes',
    thumbnail: undefined,
    tags: ['resume', 'cv', 'creative', 'designer', 'colorful', 'artistic'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-01-15T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'resume',
    aiDefinition: {
      style: 'creative',
      layoutPreset: 'two-column-equal',
      colorScheme: {
        primary: '#7c3aed',
        secondary: '#6b7280',
        accent: '#ec4899',
        textDark: '#1f2937',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 36,
        headingSize: 14,
        subheadingSize: 14,
        bodySize: 11,
        smallSize: 11,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['name', 'tagline', 'contact'],
        main: ['about', 'experience'],
        sidebar: ['skills', 'education', 'awards'],
      },
    },
  } as AITemplateMetadata,
  // Content is generated by AI - no static content
};
