import type { AITemplateMetadata, AnyTemplateData } from '../../../types/templates';

/**
 * Modern Resume Template (AI-Generated)
 * Clean, two-column layout with accent colors
 */
export const modernResumeTemplate: AnyTemplateData = {
  metadata: {
    id: 'resume-modern-001',
    name: 'Modern Resume',
    description: 'Clean, modern resume layout with two columns and accent colors',
    category: 'resumes',
    thumbnail: undefined,
    tags: ['resume', 'cv', 'modern', 'professional', 'job', 'two-column'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-01-15T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'resume',
    aiDefinition: {
      style: 'modern',
      layoutPreset: 'two-column-equal',
      colorScheme: {
        primary: '#1e293b',
        secondary: '#64748b',
        accent: '#3b82f6',
        textDark: '#1e293b',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 32,
        headingSize: 13,
        subheadingSize: 13,
        bodySize: 11,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        main: ['header', 'contact', 'profile', 'experience'],
        sidebar: ['education', 'skills'],
      },
    },
  } as AITemplateMetadata,
  // Content is generated by AI - no static content
};
