import type { AITemplateMetadata, TemplateContent, AnyTemplateData } from '../../../types/templates';

/**
 * Professional Resume Template (AI-Generated)
 * Features a dark sidebar with profile photo and main content area
 */
export const professionalResumeTemplate: AnyTemplateData = {
  metadata: {
    id: 'resume-professional-001',
    name: 'Professional Resume',
    description: 'Modern professional resume with dark sidebar, profile photo area, and clean typography',
    category: 'resumes',
    thumbnail: undefined,
    tags: ['resume', 'cv', 'professional', 'modern', 'sidebar', 'photo'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'resume',
    aiDefinition: {
      style: 'professional',
      layoutPreset: 'two-column-sidebar-left',
      colorScheme: {
        primary: '#1e2a3a',
        secondary: '#6b7280',
        accent: '#3b82f6',
        textDark: '#1e2a3a',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 36,
        headingSize: 14,
        subheadingSize: 13,
        bodySize: 11,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        sidebar: ['contact', 'skills', 'languages', 'hobbies'],
        main: ['header', 'profile', 'experience', 'education'],
      },
    },
  } as AITemplateMetadata,
  // Content is generated by AI - no static content
};
