import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Achievement Certificate Template (AI-Generated)
 * Features formal certificate design with elegant border
 */
export const achievementCertificateTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'certificate-achievement-001',
    name: 'Achievement Certificate',
    description: 'Formal achievement certificate with elegant border design for recognition and awards',
    category: 'certificates',
    thumbnail: undefined,
    tags: ['certificate', 'achievement', 'award', 'recognition', 'formal'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'certificate',
    aiDefinition: {
      style: 'achievement',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#1e3a5f',
        secondary: '#b8860b',
        accent: '#64748b',
        textDark: '#1e3a5f',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 42,
        headingSize: 20,
        subheadingSize: 18,
        bodySize: 12,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['organization', 'title'],
        main: ['presentation-text', 'recipient', 'achievement', 'description', 'date'],
        footer: ['signatures'],
      },
    },
  },
  // Content is generated by AI based on user input
};
