import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Completion Certificate Template (AI-Generated)
 * Features course/program completion certificate design
 */
export const completionCertificateTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'certificate-completion-001',
    name: 'Completion Certificate',
    description: 'Course or program completion certificate with professional styling',
    category: 'certificates',
    thumbnail: undefined,
    tags: ['certificate', 'completion', 'course', 'training', 'education'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'certificate',
    aiDefinition: {
      style: 'completion',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#059669',
        secondary: '#6b7280',
        accent: '#d1d5db',
        textDark: '#1f2937',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 36,
        headingSize: 20,
        subheadingSize: 16,
        bodySize: 12,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['organization', 'title'],
        main: ['presentation-text', 'recipient', 'course', 'hours', 'date'],
        footer: ['signatures'],
      },
    },
  },
  // Content is generated by AI based on user input
};
