import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Creative Cover Letter Template (AI-Generated)
 * Features modern, visually appealing design for creative roles
 */
export const creativeCoverLetterTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'coverletter-creative-001',
    name: 'Creative Cover Letter',
    description: 'Modern, visually appealing cover letter for creative and design roles with bold header',
    category: 'coverLetters',
    thumbnail: undefined,
    tags: ['cover letter', 'creative', 'design', 'modern', 'colorful'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'coverLetter',
    aiDefinition: {
      style: 'creative',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#7c3aed',
        secondary: '#c084fc',
        accent: '#e5e7eb',
        textDark: '#1f2937',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 32,
        headingSize: 16,
        subheadingSize: 14,
        bodySize: 11,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['name', 'tagline', 'contact-info'],
        main: ['greeting', 'opening', 'skills', 'body', 'why-company', 'closing'],
      },
    },
  },
  // Content is generated by AI based on user input
};
