import type { GenericAITemplateMetadata, TemplateContent } from '../../../types/templates';

/**
 * Professional Cover Letter Template (AI-Generated)
 * Features traditional professional layout for corporate applications
 */
export const professionalCoverLetterTemplate: { metadata: GenericAITemplateMetadata; content?: TemplateContent } = {
  metadata: {
    id: 'coverletter-professional-001',
    name: 'Professional Cover Letter',
    description: 'Traditional professional cover letter for corporate job applications with clean, formal layout',
    category: 'coverLetters',
    thumbnail: undefined,
    tags: ['cover letter', 'professional', 'job', 'application', 'corporate'],
    isPremium: false,
    version: 2,
    author: 'PDF Editor Team',
    createdAt: '2024-12-24T00:00:00Z',
    generationMode: 'ai-generated',
    inputSchema: 'coverLetter',
    aiDefinition: {
      style: 'professional',
      layoutPreset: 'single-column',
      colorScheme: {
        primary: '#1e293b',
        secondary: '#64748b',
        accent: '#0ea5e9',
        textDark: '#374151',
        textLight: '#ffffff',
        background: '#ffffff',
      },
      typography: {
        titleSize: 24,
        headingSize: 14,
        subheadingSize: 12,
        bodySize: 11,
        smallSize: 10,
        fontFamily: 'Lato',
      },
      sections: {
        header: ['name', 'contact-info'],
        main: ['date', 'recipient', 'salutation', 'opening', 'body', 'closing-paragraph', 'signature'],
      },
    },
  },
  // Content is generated by AI based on user input
};
